version: '3'

services:
  coordinator:
    image: bamcis/presto-debian:0.198
    container_name: presto_coordinator
    ports:
    - 8080:8080
    env_file:
    - ./presto.env
    networks:
    - presto
    environment:
      ROLE: coordinator
  worker0:
    image: bamcis/presto-debian:0.198
    container_name: presto_worker_0
    depends_on:
    - coordinator
    env_file:
    - ./presto.env
    environment:
      ROLE: worker
      PRESTO_DISCOVERY_SERVER: http://coordinator:8080
    networks:
    - presto
  worker1:
    image: bamcis/presto-debian:0.198
    container_name: presto_worker_1
    depends_on:
    - coordinator
    env_file:
    - ./presto.env
    environment:
      ROLE: worker
      PRESTO_DISCOVERY_SERVER: http://coordinator:8080
    networks:
    - presto

networks:
  presto:
    external: true